name: 'Setup Build Environment'
description: 'Common setup for Rust builds with all required packages (Linux & macOS)'
runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      shell: bash
      run: |
        rustup update stable
        rustup default stable
        rustup component add rustfmt clippy

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Set up Homebrew (macOS)
      if: runner.os == 'macOS'
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install packages (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: brew tap slp/krun && brew install asciidoctor libkrun clang-format llvm

    - name: Install packages (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          asciidoctor \
          libvirglrenderer-dev \
          libepoxy-dev \
          libdrm-dev \
          libpipewire-0.3-dev \
          clang-format \
          libclang-dev
        curl -OL https://github.com/containers/libkrun/archive/refs/tags/v1.17.0.tar.gz
        tar xf v1.17.0.tar.gz
        cd libkrun-1.17.0
        make
        sudo make PREFIX=/usr install
